services:
  - type: web
    name: aurora-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: DATABASE
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
